### ISSUE TITLE
Отсутствует метод на суммирование времени одного игрока в классе GameStore

### ISSUE THREAD

**Issue by ksenialyonina** [Dmitry-1994/Game_project#2]
# Описание

В классе GameStore методе addPlayTime ошибка, нет суммирования прошлого и текущего времени игрока. Нет возможности написать тест. В GameStoreTest тест закоммичен.

#  Локация дефекта
https://github.com/Dmitry-1994/Game_project/blob/e52d79cb9d9c6eeda69cda397b8905e3e6915e8c/src/main/java/ru/netology/GameStore.java#L46-L52

#  Шаги воспроизведения
1. Открыть [код программы](https://github.com/Dmitry-1994/Game_project/blob/gamestore/src/main/java/ru/netology/GameStore.java) в IDEA.

_Ожидаемый результат:_ addPlayTime добавляет время игрока и суммирует его с прошлым значением.
_Фактический результат:_ addPlayTime содержит только добавление времени игрока.

#  Скриншот
![2023-04-20_21-59-33](https://user-images.githubusercontent.com/122364592/233462237-fbd3e01d-9416-472c-8517-d2107bdc949a.png)
![2023-04-20_22-00-44](https://user-images.githubusercontent.com/122364592/233462444-1ca191cc-3310-4431-b08f-b9b005325380.png)

#  Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDEA:** IntelliJ IDEA 2022.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Dmitry-1994** [comment]
Исправлено в [`commit 760eb36`](https://github.com/Dmitry-1994/Game_project/commit/760eb36b047793e4e6fb037947cfd556023a4203)
Добавлен метод `fiendPlayedTime` в классе `GameStore`

**Comment by Dmitry-1994** [comment]
Также в [`commit 760eb36`](https://github.com/Dmitry-1994/Game_project/commit/760eb36b047793e4e6fb037947cfd556023a4203) отредактирован метод `addPlayTime` в классе `GameStore`
