### ISSUE TITLE
В классе Player отсутствует метод, возвращающий словарь игр с количеством проигранного времени 

### ISSUE THREAD

**Issue by Dmitry-1994** [Dmitry-1994/Game_project#4]
# Описание
В класс `Player` необходимо добавить метод `fiendPlayedTime`, который возвращает информацию о том, в какую игру сколько часов было сыграно.

**Comment by ksenialyonina** [comment]
Добавлен метод fiendPlayedTime в коммит https://github.com/Dmitry-1994/Game_project/commit/c0886dbcf22544bfa9a1d52df09e3d44fd15cd6a
