### ISSUE TITLE
Нет исключения при запуске неустановленной игры

### ISSUE THREAD

**Issue by Dmitry-1994** [Dmitry-1994/Game_project#5]
# Описание
В классе `Player` при вызове метода `play` не возникает исключения `RuntimeException`, если игра, передаваемая в метод, не была установлена игроком.

# Локация дефекта
https://github.com/Dmitry-1994/Game_project/blob/7d7fd2646756afd1f888b36a21762a46788ab0ec/src/main/java/ru/netology/Player.java#L39-L47

**Comment by ksenialyonina** [comment]
Исправлено в коммите https://github.com/Dmitry-1994/Game_project/commit/f3aec23ad4dd999f526909830adf48950bf3fac0
