### ISSUE TITLE
Отсутствует метод суммирования времени всех игроков в классе GameStore

### ISSUE THREAD

**Issue by ksenialyonina** [Dmitry-1994/Game_project#6]
# Описание
В классе GameStore не дописан метод getSumPlayedTime, который суммирует время всех игроков, проведенные за играми этого каталога. Сейчас он всегда возвращает 0.

#  Локация дефекта
https://github.com/Dmitry-1994/Game_project/blob/aab26a5f4b7edc476b262916221e37a81ede03d6/src/main/java/ru/netology/GameStore.java#L75-L76

#  Шаги воспроизведения
1. Открыть [код программы](https://github.com/Dmitry-1994/Game_project/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA.
2. Запустить тест sumPlayedTime.
3. Посмотреть на вывод в консоли.

_Ожидаемый результат:_ Вывод значения 110 
_Фактический результат:_ Вывод значения 0

#  Скриншоты
![2023-04-26_16-58-29](https://user-images.githubusercontent.com/122364592/234599365-548720a8-853a-45dc-87cd-3cdce41fa5d2.png)
![2023-04-26_16-58-47](https://user-images.githubusercontent.com/122364592/234599462-01f3f6e3-7ffe-4f2a-9d69-30e3b02076d7.png)
![2023-04-26_17-00-33](https://user-images.githubusercontent.com/122364592/234599706-01cf5223-d806-4d67-9d16-18da99813f97.png)

#  Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDEA:** IntelliJ IDEA 2022.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Dmitry-1994** [comment]
Исправлено в [`commit 8375d01`](https://github.com/Dmitry-1994/Game_project/commit/8375d0136aebc7dcd0c22c6800a020da42c5eec6)
