### ISSUE TITLE
Суммарное время, проигранное в игры одного жанра, рассчитывается некорректно

### ISSUE THREAD

**Issue by Dmitry-1994** [Dmitry-1994/Game_project#7]
# Описание
Суммарное время, проигранное в несколько игр одного жанра, равняется времени, проведенному в последней игре.

# Локация дефекта
https://github.com/Dmitry-1994/Game_project/blob/9523a0d00bf2b2ee2de8f1451d8434b911ba14c8/src/main/java/ru/netology/Player.java#L61-L63

# Шаги воспроизведения:
1. Открыть [код программы](https://github.com/Dmitry-1994/Game_project/tree/player) в IDEA
2. Перейти в класс `PlayerTest`
3. Запустить тест `shouldSumGenreIfSetFewGameFew`
4. Посмотреть на вывод в консоли
* **Ожидаемая результат:** actual = 8
* **Фактический результат:** actual = 5

# Скриншот
![image](https://user-images.githubusercontent.com/115424121/234961785-e7c2690a-e6c7-4363-994a-5c5cb90ac163.png)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDEA:** IntelliJ IDEA 2022.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by ksenialyonina** [comment]
Исправлено в коммите https://github.com/Dmitry-1994/Game_project/commit/1dc5d320cc1849129a08ffff7d9e1d2112f8d3ca
