### ISSUE TITLE
Выбор игры определенного жанра, в которую проиграли больше всего времени, происходит некорректно 

### ISSUE THREAD

**Issue by Dmitry-1994** [Dmitry-1994/Game_project#8]
# Описание
Метод `mostPlayerByGenre` класса `Player` всегда возвращает `null` вместо игры, в жанр которой проиграли больше всего времени. 

# Локация дефекта
https://github.com/Dmitry-1994/Game_project/blob/9523a0d00bf2b2ee2de8f1451d8434b911ba14c8/src/main/java/ru/netology/Player.java#L72-L74

# Шаги воспроизведения:
1. Открыть [код программы](https://github.com/Dmitry-1994/Game_project/tree/player) в IDEA
2. Перейти в класс `PlayerTest`
3. Запустить тест `mostPlayerByGenreFewGame`
4. Посмотреть на вывод в консоли
* **Ожидаемая результат:** тест проходит, (actual = game_2)
* **Фактический результат:** actual = null

# Скриншот
![image](https://user-images.githubusercontent.com/115424121/234965596-2e1e1c30-4dab-473d-9908-a4837bfc0398.png)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDEA:** IntelliJ IDEA 2022.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by ksenialyonina** [comment]
Исправлено в коммите https://github.com/Dmitry-1994/Game_project/commit/1dc5d320cc1849129a08ffff7d9e1d2112f8d3ca
