### ISSUE TITLE
Метод getMostPlayer не учитывает время 1 час для поиска лучшего игрока в классе GameStore 

### ISSUE THREAD

**Issue by ksenialyonina** [Dmitry-1994/Game_project#9]
# Описание
Если игрок один и сыграл 1 час, метод getMostPlayer в классе GameStore не возвращает этого игрока как bestPlayer.

#  Локация дефекта
https://github.com/Dmitry-1994/Game_project/blob/aab26a5f4b7edc476b262916221e37a81ede03d6/src/main/java/ru/netology/GameStore.java#L58-L68

#  Шаги воспроизведения
1. Открыть [код программы](https://github.com/Dmitry-1994/Game_project/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA.
2. Запустить тест showBestPlayerOneHour.
3. Посмотреть на вывод в консоли.

_Ожидаемый результат:_ Вывод игрока "Player1"
_Фактический результат:_ Вывод "null"

#  Скриншоты
![2023-04-30_11-54-07](https://user-images.githubusercontent.com/122364592/235344727-88b5777c-9959-4115-9d69-9d35ff8fa00b.png)
![2023-04-30_14-07-17](https://user-images.githubusercontent.com/122364592/235349732-be0f0522-39c5-4bb7-a7a6-3f4739a69238.png)

#  Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDEA:** IntelliJ IDEA 2022.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Dmitry-1994** [comment]
Исправлено в [commit e61bb31](https://github.com/Dmitry-1994/Game_project/commit/e61bb31977a1c56d80f2211f16755959a90056d6)
